app/forms/EnhancedMapping.scala
app/forms/MucrOptions.scala
app/views/mucr_options.scala.html
test/controllers/consolidations/MucrOptionsControllerSpec.scala
test/forms/MucrOptionsSpec.scala
test/forms/ShutMucrSpec.scala

While working on fixing this I've noticed that some scenarios are not
handled correctly. Added test suite for MucrOptions.

CEDS-1862 fix not appearing error message on MucrOptions page

---

app/controllers/ChoiceController.scala
app/forms/Choice.scala
app/views/associate_ucr_confirmation.scala.html
app/views/components/confirmation_status_info.scala.html
app/views/disassociate_ucr_confirmation.scala.html
app/views/movement_confirmation_page.scala.html
app/views/shut_mucr_confirmation.scala.html
conf/app.routes
test/controllers/ChoiceControllerSpec.scala
test/views/consolidations/ShutMucrConfirmationViewSpec.scala
test/views/disassociate_ucr/DisassociateUcrConfirmationViewSpec.scala
test/views/movement/MovementConfirmationArrivalViewSpec.scala
test/views/movement/MovementConfirmationDepartureViewSpec.scala

- Compiler now enforces the journey type is valid

CEDS Fix Next Steps links on Confirmation Pages

---

app/controllers/actions/AuthenticatedAction.scala
docs/Customs Exports Internal AutoComplete.js
test/controllers/actions/AuthenticatedActionSpec.scala

+ get rid of IDE warnings in auto complete script

CEDS Enforce ILE Enrolment

---

app/controllers/movements/GoodsDepartedController.scala
app/controllers/movements/LocationController.scala
app/forms/GoodsDeparted.scala
app/forms/MucrOptions.scala
app/models/cache/Answers.scala
app/views/goods_departed.scala.html
app/views/summary/departure_summary_page.scala.html
app/views/transport.scala.html
conf/app.routes
conf/messages.en
docs/Customs Exports Internal AutoComplete.js
test/controllers/movements/GoodsDepartedControllerSpec.scala
test/controllers/movements/LocationControllerSpec.scala
test/forms/GoodsDepartedSpec.scala
test/views/movement/DepartureSummaryViewSpec.scala
test/views/movement/GoodsDepartedViewSpec.scala
test/views/movement/TransportViewSpec.scala

This PR only adds new page into the Departure journey.
The information from the page is not going to be sent in the payload. It is for our validation only.
Mentioned validation will be delivered in a separate PR.

CEDS-1932 frustrated exports

---

app/controllers/ChoiceController.scala
app/controllers/actions/JourneyRefiner.scala
app/controllers/consolidations/AssociateUCRController.scala
app/controllers/consolidations/AssociateUCRSummaryController.scala
app/controllers/consolidations/DisassociateUCRController.scala
app/controllers/consolidations/DisassociateUCRSummaryController.scala
app/controllers/consolidations/MucrOptionsController.scala
app/controllers/consolidations/ShutMucrController.scala
app/controllers/movements/ArrivalReferenceController.scala
app/controllers/movements/ConsignmentReferencesController.scala
app/controllers/movements/GoodsDepartedController.scala
app/controllers/movements/LocationController.scala
app/controllers/movements/MovementDetailsController.scala
app/controllers/movements/MovementSummaryController.scala
app/controllers/movements/TransportController.scala
app/forms/MovementBuilder.scala
app/models/cache/Answers.scala
app/models/submissions/Submission.scala
app/repositories/CacheRepository.scala
app/services/SubmissionService.scala
test/base/MockCache.scala
test/controllers/ControllerLayerSpec.scala
test/controllers/actions/JourneyRefinerSpec.scala
test/controllers/actions/TypedJourneyRefinerTest.scala
test/controllers/movements/MovementSummaryControllerSpec.scala
test/services/SubmissionServiceSpec.scala

- Mostly just a rename of `MovementRepository` =>`CacheRepository` to match Movements
- Some Controller refactoring

CEDS-1958 Align Controller Style with Movements

---

app/views/arrival_details.scala.html
app/views/arrival_reference.scala.html
app/views/associate_ucr.scala.html
app/views/associate_ucr_summary.scala.html
app/views/choice_page.scala.html
app/views/components/submit_button.scala.html
app/views/consignment_references.scala.html
app/views/departure_details.scala.html
app/views/disassociate_ucr.scala.html
app/views/disassociate_ucr_summary.scala.html
app/views/goods_departed.scala.html
app/views/location.scala.html
app/views/mucr_options.scala.html
app/views/shut_mucr.scala.html
app/views/shut_mucr_summary.scala.html
app/views/summary/arrival_summary_page.scala.html
app/views/summary/departure_summary_page.scala.html
app/views/transport.scala.html

Moveout messages from submit button component

CEDS-1390 Save and Continue → Continue

---

app/services/SubmissionService.scala
app/services/audit/AuditService.scala
test/it/ArrivalSpec.scala
test/it/AssociateUcrSpec.scala
test/it/DepartureSpec.scala
test/it/DissociateUcrSpec.scala
test/it/IntegrationSpec.scala
test/it/ShutMucrSpec.scala
test/unit/services/audit/AuditServiceSpec.scala
test/util/connectors/AuditWiremockTestServer.scala

The principles I've gone with for the Internal UI tests are:
- Send a HTTP Request
- Verify the response code is as expected (ok/redirect)
- Verify the DB is in the expected state
- Verify any requests to other services are done as expected e.g. backend, auth
For the last point, we could consider Auditing as a request to another service. Should we verify these? Or is that going too far?

CEDS-2009 IT for audit

---

app/services/SubmissionService.scala
build.sbt
test/it/IntegrationSpec.scala
test/it/RetrospectiveArrivalSpec.scala
test/unit/services/audit/AuditServiceSpec.scala

Missing update after comments under previous PR.
Also, increased minimum coverage to 80%.

CEDS-1915 retrospective arrivals

---

conf/schemas/exports/inventoryLinkingCommonTypes.xsd
conf/schemas/exports/inventoryLinkingCore.xsd
conf/schemas/exports/inventoryLinkingRequestExternal.xsd
conf/schemas/exports/inventoryLinkingResponseExternal.xsd

This is to serve just as a reference point. No need to browse other
repositories.

Add ILE schemas to the project

---

project/AppDependencies.scala

This should clear problem with “No primary node is available!”

CEDS Update simple-reactivemongo

---

project/AppDependencies.scala

This version is compatibile with MongoDB version 3.6

Update mongo driver to latest one for mongobee

---

app/views/components/summary_list_original.scala.html
app/views/location.scala.html
app/views/summary/departure_summary_page.scala.html
app/views/summary/retrospective_arrival_summary_page.scala.html
test/unit/views/movement/LocationViewSpec.scala

View reformatted.  Main change is the restoration of the back link url depending on journey type.

BAU - restore functionality of back button on location page

---

app/views/disassociate_ucr.scala.html
app/views/disassociate_ucr_summary.scala.html
test/unit/controllers/consolidations/DisassociateUCRControllerSpec.scala
test/unit/controllers/consolidations/DisassociateUCRSummaryControllerSpec.scala
test/unit/views/disassociate_ucr/DisassociateUcrSummaryViewSpec.scala
test/unit/views/disassociate_ucr/DisassociateUcrViewSpec.scala

- Introduce GDS design to Dissociate UCR page
- Introduce GDS design on Dissociate UCR summary page

CEDS-2127 Internal Movements: Dissociate Journey to Gov Design System

---

app/controllers/movements/GoodsDepartedController.scala
app/controllers/movements/LocationController.scala
app/views/goods_departed.scala.html
app/views/location.scala.html
conf/messages.en
test/unit/controllers/movements/GoodsDepartedControllerSpec.scala
test/unit/controllers/movements/LocationControllerSpec.scala
test/unit/views/movement/GoodsDepartedViewSpec.scala
test/unit/views/movement/LocationViewSpec.scala

This PR fixes Section Header on Location page for Retrospective Arrival.
Additionally, a section header has been added to Goods Location page.

CEDS-2130 retro arrival location fix

---

app/views/associateucr/associate_ucr_summary.scala.html

When list has mixture of actions and no actions

CEDS-2609 - workaround for accessibility issue with SummaryList

---

app/models/viewmodels/decoder/CRCCode.scala
conf/messages-notification-codes-exports.en
test/unit/models/viewmodels/decoder/CRCCodeSpec.scala

CRC code 102 content changed to 'Declaration has not arrived'

CEDS-2679 Update content for CRC code 102

---

app/views/components/gds/link.scala.html
app/views/view_submissions.scala.html
conf/messages.en
test/unit/views/ViewSubmissionsViewSpec.scala
test/util/testdata/CommonTestData.scala

- Create option for visually hidden text on link component
- Use link with hidden text on submissions page

CEDS-2689 Add hidden text with context for movements

---

conf/messages.en

Add full stops to the end of error messages

CEDS-2736 Update error messages to be consistent

---

app/models/viewmodels/decoder/SOECode.scala
conf/messages-notification-codes-cds.en
conf/messages-notification-codes-exports.en
test/unit/models/viewmodels/decoder/SOECodeSpec.scala

For this PR to be ready, the content for code description needs to be added.

CEDS-2734 Empty MUCR SOE code in EMR notification handling

---

app/repositories/CacheRepository.scala
app/repositories/IleQueryRepository.scala
app/repositories/RepositorySettings.scala

This is in order to increase resilience of the service.

CEDS-2776 Implement FailoverStrategy for all repository classes

---

app/assets/stylesheets/customsdecexfrontend-app.scss
app/config/AppConfig.scala
app/views/components/gds/gds_main_template.scala.html
project/AppDependencies.scala

This reverts commit 6bea5325bda15d68c5d92204718877dd5eb3d199.
This being an Internal HMRC service it does not require this
functionality.

CEDS-2667 Remove HMRCReportTechnicalssue component

---

app/controllers/RootController.scala
conf/app.routes
test/unit/controllers/RootControllerSpec.scala

Create RootController to redirect to Find Consignment page.

CEDS-2965 Set Root Url to redirect to home page

---

app/services/Countries.scala
test/unit/views/components/summary/TransportSummaryListViewSpec.scala

Following Tim's country dropdown fix, this is what the formatting looks like in EDS now.

CEDS-3650 Correct country string formatting

---

app/models/cache/Cache.scala
project/plugins.sbt

Reverts hmrc/customs-exports-internal-frontend#261
Don't want to accidentally redeploy this code without the fix due to be applied in https://jira.tools.tax.service.gov.uk/browse/CEDS-4532

Revert "CEDS-4350 Add correct instant format to cache so that TTL will be eff…"
