- app/controllers/ChoiceController.scala
- app/controllers/consolidations/AssociateUCRConfirmationController.scala
- app/controllers/consolidations/AssociateUCRSummaryController.scala
- app/controllers/consolidations/DisassociateUCRConfirmationController.scala
- app/controllers/consolidations/DisassociateUCRController.scala
- app/controllers/consolidations/DisassociateUCRSummaryController.scala
- app/controllers/consolidations/ShutMUCRConfirmationController.scala
- app/controllers/movements/MovementConfirmationController.scala
- app/controllers/movements/SummaryController.scala
- app/controllers/storage/FlashKeys.scala
- app/views/disassociate_ucr.scala.html
- app/views/disassociate_ucr_confirmation.scala.html
- app/views/disassociate_ucr_summary.scala.html
- app/views/movement_confirmation_page.scala.html
- conf/app.routes
- test/controllers/ChoiceControllerSpec.scala
- test/controllers/consolidations/AssociateUCRConfirmationControllerSpec.scala
- test/controllers/consolidations/AssociateUCRSummaryControllerSpec.scala
- test/controllers/consolidations/DisassociateUCRConfirmationControllerSpec.scala
- test/controllers/consolidations/DisassociateUCRControllerSpec.scala
- test/controllers/consolidations/DisassociateUCRSummaryControllerSpec.scala
- test/controllers/consolidations/ShutMUCRConfirmationControllerSpec.scala
- test/controllers/consolidations/ShutMucrSummaryControllerSpec.scala
- test/controllers/movements/MovementConfirmationControllerSpec.scala
- test/controllers/movements/SummaryControllerSpec.scala
- test/views/disassociate_ucr/DisassociateUcrConfirmationViewSpec.scala
- test/views/disassociate_ucr/DisassociateUcrSummaryViewSpec.scala
- test/views/disassociate_ucr/DisassociateUcrViewSpec.scala
- test/views/movement/MovementConfirmationArrivalViewSpec.scala
- test/views/movement/MovementConfirmationDepartureViewSpec.scala
It was previously POST -> show view
This means that a refresh of the confirmation screen would re-submit the movement/consolidation
> CEDS-1940 Fix Confirmation POST/Redirect/GET logic

- app/controllers/movements/LocationController.scala
- app/controllers/movements/MovementSummaryController.scala
- app/controllers/movements/TransportController.scala
- app/forms/Choice.scala
- app/views/disassociate_ucr_confirmation.scala.html
- app/views/shut_mucr_confirmation.scala.html
- app/views/summary/arrival_summary_page.scala.html
- app/views/summary/departure_summary_page.scala.html
- conf/app.routes
- conf/messages.en
- test/controllers/movements/LocationControllerSpec.scala
- test/controllers/movements/MovementSummaryControllerSpec.scala
- test/controllers/movements/TransportControllerSpec.scala
- test/views/consolidations/ShutMucrConfirmationViewSpec.scala
- test/views/disassociate_ucr/DisassociateUcrConfirmationViewSpec.scala
Key Changes:
- Ensure ucr type is Upper case e.g. `MUCR` or `DUCR` instead of `mucr` or `ducr`
- Align ViewSubmissions choice code with Movements
- Fix ShutMUCR tab title that just rendered the message key
- `SummaryController` => `MovementSummaryController`
> CEDS-1940 Acceptance Test  Fixes

- app/controllers/movements/TransportController.scala
- app/forms/Transport.scala
- app/forms/providers/TransportFormProvider.scala
- conf/messages.en
- test/controllers/movements/TransportControllerSpec.scala
- test/forms/TransportSpec.scala
- test/forms/providers/TransportFormProviderSpec.scala
- test/views/movement/TransportViewSpec.scala
To give you some context:
Validation on Transport page is different depending on the users choice on GoodsDeparted page. In this PR you can see both validations/mappings added and the logic for providing correct form with the mapping.
There are 2 mappings added for different export scenarios:
1. Out of the UK
2. Back into the UK
Also, there is TransportFormProvider added. To separate logic for
providing correct form and to simplify tests.
> CEDS-1932 Change Transport validation

- app/services/audit/AuditService.scala
- test/it/ArrivalSpec.scala
- test/it/AssociateUcrSpec.scala
- test/it/DepartureSpec.scala
- test/it/DissociateUcrSpec.scala
- test/it/IntegrationSpec.scala
- test/it/ShutMucrSpec.scala
- test/unit/services/audit/AuditServiceSpec.scala
They were removed previously as they were flakey
This is because the submission service doesn't chain the future returned by the AuditService so it completes in parallel, not necessarily before the verify is called.
The behaviour above is desired, we don't want to couple the success of a submission to whether the Audit Service is up & performant, so I've changed the tests to `verifyEventually` instead of immediately
> CEDS-2046 Re-Enable Audit ITs

- app/services/audit/AuditService.scala
- app/services/audit/AuditType.scala
- test/it/ArrivalSpec.scala
- test/it/AssociateUcrSpec.scala
- test/it/DepartureSpec.scala
- test/it/DissociateUcrSpec.scala
- test/it/RetrospectiveArrivalSpec.scala
- test/it/ShutMucrSpec.scala
- test/unit/services/audit/AuditServiceSpec.scala
- upper case characters in paths changed to lower case
- Retrospective Arrival and ShutMucr names separated with "-", e.g.:
retrospective-arrival
- "providerId" key changed into "pid"
> Change AuditEvents contents

- app/forms/common/Date.scala
- app/forms/common/Time.scala
- conf/messages.en
- test/unit/forms/DepartureDetailsSpec.scala
- test/unit/forms/common/DateSpec.scala
- test/unit/forms/common/TimeSpec.scala
- test/util/matchers/FormMatchers.scala
There was a problem making some of our regression tests failing. It was
non-deterministic and hard to reason about.
The cause turned out to be the DateTime formatting and displaying those
on the pages. The pattern is to have 2 digit hour and minute but the
previous implementation did not cover that.
The solution is a copy from External Movements service, where the same
problem has been resolved.
> Fix Date and Time forms

- app/controllers/consolidations/AssociateUCRConfirmationController.scala
- app/controllers/consolidations/AssociateUCRSummaryController.scala
- app/views/associate_ucr_confirmation.scala.html
- test/unit/controllers/consolidations/AssociateUCRConfirmationControllerSpec.scala
- test/unit/controllers/consolidations/AssociateUCRSummaryControllerSpec.scala
- test/unit/views/associate_ucr/AssociateUCRConfirmationViewSpec.scala
This is a feature branch to consolidate merges from all related page-specific branches:
* CEDS-2098-arrive (affects departure and retrospective arrival) - ok
* CEDS-2098-associate - ok
* CEDS-2098-disassociate - TODO
* CEDS-2098-shut - TODO
* CEDS-2098-clean - TODO
It is an alternative confirmation screen to implement in the internal service as a way of avoiding cases being closed when they shouldn't be.
Currently, NCH operators see the existing confirmation screen at the end of each movement request journey and believe that it means their request has been completed and accepted. As their request has only been submitted to DMS and the acceptance (or rejection) is asynchronous, this could be misleading.
> CEDS-2098 - Associate UCR page

- app/controllers/consolidations/DisassociateUCRConfirmationController.scala
- app/views/disassociate_ucr_confirmation.scala.html
- test/unit/controllers/consolidations/AssociateUCRConfirmationControllerSpec.scala
- test/unit/controllers/consolidations/DisassociateUCRConfirmationControllerSpec.scala
- test/unit/views/disassociate_ucr/DisassociateUcrConfirmationViewSpec.scala
This is a feature branch to consolidate merges from all related page-specific branches:
* CEDS-2098-arrive (affects departure and retrospective arrival) - ok
* CEDS-2098-associate - ok
* CEDS-2098-disassociate - ok
* CEDS-2098-shut - TODO
* CEDS-2098-clean - TODO
It is an alternative confirmation screen to implement in the internal service as a way of avoiding cases being closed when they shouldn't be.
Currently, NCH operators see the existing confirmation screen at the end of each movement request journey and believe that it means their request has been completed and accepted. As their request has only been submitted to DMS and the acceptance (or rejection) is asynchronous, this could be misleading.
> CEDS-2098 - Disassociate UCR page

- app/controllers/consolidations/ShutMUCRConfirmationController.scala
- app/views/shut_mucr_confirmation.scala.html
- test/unit/controllers/consolidations/ShutMUCRConfirmationControllerSpec.scala
- test/unit/views/consolidations/ShutMucrConfirmationViewSpec.scala
This is a feature branch to consolidate merges from all related page-specific branches:
* CEDS-2098-arrive (affects departure and retrospective arrival) - ok
* CEDS-2098-associate - ok
* CEDS-2098-disassociate - ok
* CEDS-2098-shut - ok
* CEDS-2098-clean - TODO
It is an alternative confirmation screen to implement in the internal service as a way of avoiding cases being closed when they shouldn't be.
Currently, NCH operators see the existing confirmation screen at the end of each movement request journey and believe that it means their request has been completed and accepted. As their request has only been submitted to DMS and the acceptance (or rejection) is asynchronous, this could be misleading.
> CEDS-2098 - Shut MUCR page

- app/controllers/movements/MovementConfirmationController.scala
- app/views/movement_confirmation_page.scala.html
- conf/messages.en
- test/unit/controllers/movements/MovementConfirmationControllerSpec.scala
- test/unit/views/movement/MovementConfirmationArrivalViewSpec.scala
- test/unit/views/movement/MovementConfirmationDepartureViewSpec.scala
- test/unit/views/movement/MovementConfirmationRetrospectiveArrivalViewSpec.scala
This is a feature branch to consolidate merges from all related page-specific branches:
* CEDS-2098-arrive (affects departure and retrospective arrival) - ok
* CEDS-2098-associate - ok
* CEDS-2098-disassociate - ok
* CEDS-2098-shut - ok
* CEDS-2098-clean - TODO
It is an alternative confirmation screen to implement in the internal service as a way of avoiding cases being closed when they shouldn't be.
Currently, NCH operators see the existing confirmation screen at the end of each movement request journey and believe that it means their request has been completed and accepted. As their request has only been submitted to DMS and the acceptance (or rejection) is asynchronous, this could be misleading.
> CEDS-2098 - Clean-up

- app/controllers/ChoiceController.scala
- app/controllers/actions/JourneyRefiner.scala
- app/controllers/ileQuery/IleQueryController.scala
- app/models/cache/Cache.scala
- test/it/IntegrationSpec.scala
- test/unit/controllers/consolidations/DisassociateUCRControllerSpec.scala
- test/unit/controllers/ileQuery/IleQueryControllerSpec.scala
- test/unit/controllers/movements/ConsignmentReferencesControllerSpec.scala
- test/unit/controllers/movements/GoodsDepartedControllerSpec.scala
- test/unit/controllers/movements/LocationControllerSpec.scala
This PR saves the queried ucr and type as part of the viewing of ILE Query Results to the users cache.  
Nothing is done with that saved data at present, but it will be used in future to integrate the queried ucr into the various journeys (i.e. to pre-fill questions or even skip pages)
> CEDS-2102 - store queried ucr and type as preparation for journeys

- app/controllers/ChoiceController.scala
- app/views/choice_page.scala.html
- test/unit/controllers/ChoiceControllerSpec.scala
- test/unit/views/ChoicePageViewSpec.scala
This should link back to the consignment details for the previous ILE Query search (re-submitting the search as part of the process).
The link is only rendered if we have a UcrBlock present in the users cache (which in turn only gets added to the cache upon the successful completion of an ILE search).
> CEDS-2093 - add back button to choice page 

- build.sbt
This is due to a failed deployment to `externaltest` environement where
an error was found:
```
java.lang.IllegalArgumentException: Last encoded character (before the
paddings if any) is a valid base 64 alphabet but not a possible value
```
This is to do with an incorrect sso encryption key being used in
externaltest and the latest version of `simple-reactivemongo` uses the
latest `commons-codec v1.13` which detects this as an issue and the
deployment fails.
This has been discussed with Colin Webb and Lewis Capaldi.
This is the last resort attempt to deploy the applications to
`externaltest` whilst HMRC Platform team look into the issue.
> CEDS-2029 Force use of commons-codec v1.12

- app/mongobee/MongobeeConfig.scala
This solves the problem that Mongobee was not closing opened DB
connections after execution. This was causing Mongo to crash during unit
tests execution (over 100 new connections were created).
> Close Mongobee runner after execution

- app/models/cache/Cache.scala
- app/mongobee/changesets/CacheChangelog.java
- test/unit/controllers/ChoiceControllerSpec.scala
Same change as external movements frontend service - 
- added new "updated" field to cache model with default of "now"
- updated the db (using Mongobee) to add field to existing cache objects and add ttl index to cache collection
> CEDS-2164 - add TTL of 60 mins to cache

- app/config/AppConfig.scala
- app/mongobee/changesets/IleQueriesChangelog.java
- app/repositories/IleQueryRepository.scala
- conf/application.conf
This change is not strictly necessary but it keeps the creation of indexes consistent (i.e. in the mongobee changelog scripts).
In addition, it solves the problem that the ttl timeout value was not changeable via the config (if the db already had the index).
> BAU - move creation of IleQueries ttl index to mongobee changelog

- app/models/cache/Cache.scala
Exising cache data cannot be migrated and we can't manually drop db in
prod., so new fields have to be optional.
> CEDS-2164 - make 'updated' field optional

- app/config/AppConfig.scala
- app/controllers/ChoiceController.scala
- app/views/components/confirmation_link.scala.html
- app/views/components/gds/exportsInputText.scala.html
- app/views/ile_query.scala.html
- app/views/view_submissions.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- conf/testOnlyDoNotUseInAppConf.routes
- test/it/ArrivalSpec.scala
- test/it/AssociateUcrSpec.scala
- test/it/ChoiceSpec.scala
- test/it/DepartureSpec.scala
- test/it/DissociateUcrSpec.scala
- test/it/IntegrationSpec.scala
- test/it/RetrospectiveArrivalSpec.scala
- test/it/ShutMucrSpec.scala
- test/unit/controllers/ChoiceControllerSpec.scala
- test/unit/views/IleQueryViewSpec.scala
- test/unit/views/components/ConfirmationLinkViewSpec.scala
The "Find a consignment" became the first step in the `customs-exports-internal-frontend` so that NCH operators can search for a consignment before acting on it. When a user logs in to the service, the first screen they see now is the search screen, and she/he cannot access the 'What do you want to do?' screen directly. If a user navigates away from the query page, it is possible to get back using the back button. There is a link to the consignment detail screen as well.
> CEDS-2100 - Make searching for a consignment the first step in the service

- app/models/notifications/queries/IleQueryResponseExchangeData.scala
- app/models/viewmodels/decoder/ROECode.scala
- app/models/viewmodels/ilequery/IleQueryCodeConverter.scala
- app/views/components/ilequery/response_associated_consignments.scala.html
- app/views/components/ilequery/response_buttons.scala.html
- app/views/components/ilequery/response_ducr_summary.scala.html
- app/views/components/ilequery/response_mucr_summary.scala.html
- app/views/components/ilequery/response_parent.scala.html
- app/views/components/ilequery/response_previous_movements.scala.html
- app/views/ile_query_ducr_response.scala.html
- app/views/ile_query_mucr_response.scala.html
- conf/messages.en
- test/unit/models/viewmodels/decoder/ROECodeSpec.scala
- test/unit/models/viewmodels/notificationspage/converters/EMRResponseConverterSpec.scala
- test/unit/models/viewmodels/notificationspage/converters/ERSResponseConverterSpec.scala
- test/unit/views/IleQueryDucrResponseViewSpec.scala
- test/unit/views/IleQueryMucrResponseViewSpec.scala
- test/unit/views/components/ilequery/AssociatedConsignmentsViewSpec.scala
- test/unit/views/components/ilequery/DucrSummaryViewSpec.scala
- test/unit/views/components/ilequery/MucrSummaryViewSpec.scala
- test/unit/views/components/ilequery/ParentViewSpec.scala
- test/unit/views/components/ilequery/PreviousMovementsViewSpec.scala
- Omit table rows with no values (codes)
- Hide movements table when empty
- Move submit button & link up under Queried UCR section
- Fixed bug whereby unknown route of entry was displayed as "Unknown"
rather than "<code> - Unknown"
- Took the opportunity to break up the existing view specs in favour of
smaller tests for each component.
> CEDS-2177 - Improvements to Queried UCR page

- conf/messages.en
A consistent naming convention must be displayed across all three CDS Exports services to provide users for a simplified experience and understanding.
The CDS Movements Exports service was modified to:
1) the service name changed to CDS Exports in the banners at the top of each page,
2) the service name changed to CDS Exports on the start page.
> CEDS-2057 - Rename the Export services

- app/views/shutmucr/shut_mucr_summary.scala.html
- test/unit/views/shutmucr/ShutMucrSummaryViewSpec.scala
**Shut Mucr page change button removed.**
The Internal and External Movements Services are being changed to force users to query before performing an action in order to reduce the risk that a movement is inadvertently performed against the wrong UCR. Therefore, it doesn't make sense to give users the option to change the UCR when managing the queried consignment.
After searching for a valid UCR and proceeding to the next page via  'Manage this Consignment' button, following any action to perform against this UCR (e.g. Arrive, Depart, Shut, Disassociate, Retrospective Arrival), it must be not possible to change the UCR.
> CEDS-2199 - Prevent changes to UCR when Managing Consignment

- app/views/components/ilequery/response_ducr_summary.scala.html
- conf/messages.en
- test/unit/views/components/ilequery/DucrSummaryViewSpec.scala
A queried DUCR must show the MRN on the results page. In contrast, there must be no MRN displayed on the results page when a MUCR is queried.
> CEDS-2214 - Internal Movements: Add MRN to Movements Query results page

- app/assets/stylesheets/partials/_autocomplete.scss
- app/views/ducr_part_details.scala.html
Change find Ducr Part input field to width-20 (works better with larger fonts)
> CEDS-2612 - auto-complete drop-down arrow location relative to font size

- app/views/associateucr/associate_ucr_summary.scala.html
- app/views/disassociateucr/disassociate_ucr_summary.scala.html
- app/views/shutmucr/shut_mucr_summary.scala.html
- app/views/summary/arrival_summary_page.scala.html
- app/views/summary/departure_summary_page.scala.html
- app/views/summary/retrospective_arrival_summary_page.scala.html
This change is to make Summary pages more accessible when used with
double-sized font.
Many words were split into multiple lines which was an issue.
> CEDS-2614 Change Summary pages to full width

- app/assets/stylesheets/customsdecexfrontend-app.scss
- app/config/AppConfig.scala
- app/views/components/gds/gds_main_template.scala.html
- project/AppDependencies.scala
This component is a non-ajax implementation and is the recommended
approach by the HMRC Play UI team, since the previous "GetHelpLink" was
not accessible.
This component does not work locally and it should simply open a new
page. We have been told that this will work in all the other
environments.
> CEDS-2667 Add HMRCReportTechnicalssue component

- app/utils/FieldValidator.scala
- test/unit/forms/AssociateUcrSpec.scala
- test/unit/forms/ConsignmentReferencesSpec.scala
- test/unit/forms/DisassociateUcrSpec.scala
- test/unit/forms/IleQueryFormSpec.scala
- test/unit/forms/ShutMucrSpec.scala
Recently we have encountered the issue with following MUCR:
`GB/82F9-0N2F6500040010TO120P0A300689` (36 characters long)
It complies with our regex but it was over 35 characters long and ILE
rejected for being too long.
After speaking with the QAs we have determined that the regex requires
an overal length validation.
The approach taken was not to overload the existing regex, it is already
too complex to read and instead add a separate validation on it's
length.
> CEDS-2771 Validate MUCR length is <36 characters long

- conf/application.conf
Upgrade of assets-frontend repository from 3.3.2 -> 3.17.0 to
plug a security vulnerability hilighted by the recent pen test.
> [CEDS-3162] Plug JQuery Vulnerability

- app/controllers/SignOutController.scala
- test/unit/controllers/SignOutControllerSpec.scala
Authentication on this endpoint is not necessary, as the
session is removed on this endpoint anyway.
Additionally, requirement to be authenticated on this
endpoint was causing random problems, because sometimes
user was asked to log-in to be then logged out. This
was probably due to auth cookie timing out slightly
before this endpoint was hit.
> CEDS-3163 Remove authentication from /sign-out endpoint

- conf/application.conf
To meet splunk storage requirements.
> CEDS-3650 Add config to stop auditing asset requests

- app/models/cache/Cache.scala
- project/plugins.sbt
- test/unit/models/cache/AnswersSpec.scala
Add defensive reads so that updated fields is read as a string or Date
Ensure all new records are written with a Date to the updated field
> CEDS-4532 Update reads and writes for Cache
